apiVersion: v1
kind: ReplicationController
metadata:
  name: nama-replication-controller
  labels:
    label-key: label-value
  annotations:
    annotation-key: annotation-value
spec:
  replicas: 3
  selector:
    label-key: label-value
  template:
    metadata:
      name: nama-pod
      labels:
        label-key: label-value
    spec:
      containers:
        - name: container-name
          image: image-name
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
