apiVersion: v1
kind: Pod
metadata:
  name: okedok-consumer
  namespace: okedok
spec:
  containers:
    - name: okedok-3rdparty
      image: pisckitama/okedok-3rd-party:1.1
      env:
      - name: MAILGUN_API_KEY
        valueFrom:
          secretKeyRef: 
            name: okedok-secret
            key: mailgun-key
      - name: MAILGUN_DOMAIN
        valueFrom:
          secretKeyRef: 
            name: okedok-secret
            key: mailgun-domain
      - name: KAFKA_BROKER
        valueFrom:
          secretKeyRef:
            name: okedok-secret
            key: kafka-broker
      - name: EMAIL_NAME
        valueFrom:
          configMapKeyRef: 
            name: okedok-configmap
            key: email-name
      - name: EMAIL_ADDRESS
        valueFrom:
          configMapKeyRef:
            name: okedok-configmap
            key: email-address
