apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-app
  namespace: okedok
  labels:
    app: kafka
    tier: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      tier: broker
  template:
    metadata:
      name: kafka-app
      namespace: okedok
      labels:
        app: kafka
        tier: broker
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://localhost:9092"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: okedok
  labels:
    app: kafka
    tier: broker
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
    tier: broker