apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: okedok
  labels:
    app: okedok
    tier: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okedok
      tier: broker
  template:
    metadata:
      name: zookeeper
      namespace: okedok
      labels:
        app: okedok
        tier: broker
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: okedok
  labels:
    app: okedok
    tier: broker
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: okedok
    tier: broker