apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-depl
  labels:
    app: mongodb-depl
    tier: database
spec:
  replicas: 2
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb-depl
    spec:
       volumes:
         - name: mongodbdata
           persistentVolumeClaim:
             claimName: mongodb-pv-claim
       containers:
       - name: mongodb
         image: mongo
         volumeMounts:
           - mountPath: /data/db
             name: mongodbdata
         ports:
           - containerPort: 27017
         env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
  selector:
    matchLabels:
      app: mongodb-depl
