apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: 'postgres'
    version: '12'
data:
  POSTGRES_DB: 'okedok_dev'
  POSTGRES_USER: 'okedok'
  POSTGRES_PASSWORD: 'P@ssw0rd123!'
