apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-depl
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30003
  selector:
    app: postgres-depl
