apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-role-binding
  namespace: development
subjects:
- kind: User
  name: devops
roleRef:
  kind: Role
  name: devops
  apiGroup: rbac.authorization.k8s.io
