apiVersion: apps/v1
kind: Deployment
metadata:
  name: okedok-redis
  namespace: okedok
  labels:
    app: okedok
    tier: caching
spec:
  replicas: 2
  template:
    metadata:
      name: okedok-redis
      labels:
        app: okedok
        tier: caching
    spec:
      containers:
      - name: redis
        image: redis:6.2.1-alpine3.13
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: example-redis-config
            items:
            - key: redis-config
              path: redis.conf
  selector:
    matchLabels:
      app: okedok
      tier: caching