apiVersion: v1
kind: Service
metadata:
  name: okedok-redis
  namespace: okedok
  labels:
    app: okedok
    tier: caching
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: okedok
    tier: caching
