apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - httpd
      - key: env
        operator: In
        values:
          - prod
          - qa
          - dev
  template:
    metadata:
      name: httpd-rs
      labels:
        app: httpd
        env: prod
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
