apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
spec:
  replicas: 3
  selector:
    app: httpd
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
