apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      name: httpd
  template:
    metadata:
      name: httpd
      labels:
        name: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
        - name: nodejs-web
          image: pisckitama/nodejs-web
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    name: httpd
  ports:
    - port: 8080
      targetPort: 80
      name: httpd
    - port: 3000
      targetPort: 3000
      name: nodejs-web

---
apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    name: curl
spec:
  containers:
    - name: curl
      image: pisckitama/httpd-curl
