apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      name: httpd
  template:
    metadata:
      name: httpd
      labels:
        name: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: LoadBalancer
  selector:
    name: httpd
  ports:
    - port: 80
      targetPort: 80
