apiVersion: apps/v1
kind: Deployment
metadata:
  name: okechat
  namespace: okedok
  labels:
    name: okechat
spec:
  replicas: 2
  selector:
    matchLabels:
      name: okechat
  template:
    metadata:
      name: okechat
      labels:
        name: okechat
    spec:
      containers:
        - name: okechat
          image: harbor.lab.local/okedok/okechat:1.0
          ports:
            - containerPort: 8802

---
apiVersion: v1
kind: Service
metadata:
  name: okechat-service
  namespace: okedok
spec:
  selector:
    name: okechat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8802
      name: http
    - protocol: TCP
      port: 443
      targetPort: 8802
      name: https
  type: LoadBalancer
