---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: nfs
spec:
   storageClassName: qa
   capacity:
     storage: 1Gi
   accessModes:
     - ReadWriteMany
   nfs:
     server: 10.0.0.5
     path: "/mnt/nfsdir"
